import { useParams } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { motion } from 'framer-motion'
import {
  AlertTriangle,
  Droplets,
  FileSearch,
  HeartPulse,
  Phone,
  Pill,
  ShieldCheck,
  Stethoscope,
  StickyNote,
} from 'lucide-react'
import { GlassCard } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Skeleton } from '@/components/ui/skeleton'
import { profileApi } from '@/features/profile/api'
import { fadeUp, staggerContainer } from '@/lib/motion'
import { getInitials } from '@/lib/utils'

function InfoSection({
  icon: Icon,
  title,
  value,
  tone = 'default',
}: {
  icon: typeof Pill
  title: string
  value: string | null
  tone?: 'default' | 'warning'
}) {
  if (!value) return null
  return (
    <motion.div variants={fadeUp}>
      <GlassCard
        className={`p-5 ${tone === 'warning' ? 'border-amber-500/40 bg-amber-500/5' : ''}`}
      >
        <p className="mb-1.5 flex items-center gap-2 text-xs font-semibold tracking-wider uppercase text-muted-foreground">
          <Icon
            className={`h-4 w-4 ${tone === 'warning' ? 'text-amber-500' : 'text-primary'}`}
          />
          {title}
        </p>
        <p className="text-[15px] leading-relaxed whitespace-pre-wrap">{value}</p>
      </GlassCard>
    </motion.div>
  )
}

export default function PublicMedicalIdPage() {
  const { token } = useParams<{ token: string }>()

  const medicalIdQuery = useQuery({
    queryKey: ['medical-id', token],
    queryFn: () => profileApi.getPublicMedicalId(token!),
    enabled: !!token,
    retry: 1,
  })

  if (medicalIdQuery.isPending) {
    return (
      <div className="mx-auto max-w-lg space-y-4 px-4 py-10">
        <Skeleton className="h-32" />
        <Skeleton className="h-24" />
        <Skeleton className="h-40" />
      </div>
    )
  }

  if (medicalIdQuery.isError) {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center px-5 text-center">
        <span className="glass-panel mb-6 flex h-16 w-16 items-center justify-center rounded-2xl">
          <FileSearch className="h-8 w-8 text-muted-foreground" />
        </span>
        <h1 className="font-display text-2xl font-bold">Medical ID not found</h1>
        <p className="mt-2 max-w-sm text-sm text-muted-foreground">
          This link is invalid, has been regenerated by its owner, or the Medical ID was disabled.
        </p>
      </div>
    )
  }

  const data = medicalIdQuery.data
  const meta = [
    data.age !== null ? `${data.age} yrs` : null,
    data.gender,
    data.heightCm ? `${data.heightCm} cm` : null,
    data.weightKg ? `${data.weightKg} kg` : null,
  ].filter(Boolean)

  return (
    <div className="min-h-screen pb-14">
      {/* Emergency header */}
      <div className="bg-gradient-to-r from-rose-600 via-red-600 to-rose-600 px-4 py-3 text-center">
        <p className="flex items-center justify-center gap-2 text-sm font-bold tracking-widest text-white uppercase">
          <AlertTriangle className="h-4 w-4" />
          Emergency Medical ID
        </p>
      </div>

      <motion.div
        variants={staggerContainer}
        initial="hidden"
        animate="show"
        className="mx-auto max-w-lg space-y-4 px-4 pt-6"
      >
        {/* Identity */}
        <motion.div variants={fadeUp}>
          <GlassCard className="flex items-center gap-4 p-5">
            <div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-blue-500 to-violet-500 text-lg font-bold text-white">
              {getInitials(data.fullName)}
            </div>
            <div className="min-w-0">
              <h1 className="font-display text-xl font-bold">{data.fullName}</h1>
              {meta.length > 0 && (
                <p className="text-sm text-muted-foreground">{meta.join(' · ')}</p>
              )}
              {data.organDonor && (
                <Badge variant="success" className="mt-1.5">
                  <ShieldCheck className="h-3 w-3" /> Organ donor
                </Badge>
              )}
            </div>
          </GlassCard>
        </motion.div>

        {/* Blood group — the most critical fact, biggest on screen */}
        {data.bloodGroup && (
          <motion.div variants={fadeUp}>
            <div className="rounded-2xl border border-emergency/40 bg-emergency/10 p-6 text-center">
              <p className="flex items-center justify-center gap-2 text-xs font-semibold tracking-wider text-emergency uppercase">
                <Droplets className="h-4 w-4" /> Blood group
              </p>
              <p className="font-display mt-1 text-6xl font-bold text-emergency">
                {data.bloodGroup}
              </p>
            </div>
          </motion.div>
        )}

        <InfoSection icon={AlertTriangle} title="Allergies" value={data.allergies} tone="warning" />
        <InfoSection icon={Stethoscope} title="Medical conditions" value={data.medicalConditions} />
        <InfoSection icon={Pill} title="Current medications" value={data.medications} />
        <InfoSection icon={StickyNote} title="Emergency notes" value={data.emergencyNotes} />
        <InfoSection
          icon={ShieldCheck}
          title="Insurance"
          value={
            data.insuranceProvider
              ? `${data.insuranceProvider}${data.insurancePolicyNumber ? ` · ${data.insurancePolicyNumber}` : ''}`
              : null
          }
        />

        {/* Emergency contacts with one-tap calling */}
        {data.emergencyContacts.length > 0 && (
          <motion.div variants={fadeUp}>
            <GlassCard className="p-5">
              <p className="mb-3 flex items-center gap-2 text-xs font-semibold tracking-wider uppercase text-muted-foreground">
                <Phone className="h-4 w-4 text-primary" /> Emergency contacts
              </p>
              <div className="space-y-2.5">
                {data.emergencyContacts.map((contact) => (
                  <a
                    key={`${contact.name}-${contact.phone}`}
                    href={`tel:${contact.phone}`}
                    className="flex items-center justify-between gap-3 rounded-xl border border-border p-3.5 transition-colors hover:border-success/50 hover:bg-success/5"
                  >
                    <div className="min-w-0">
                      <p className="truncate font-medium">
                        {contact.name}
                        {contact.relationship && (
                          <span className="ml-2 text-xs text-muted-foreground">
                            {contact.relationship}
                          </span>
                        )}
                      </p>
                      <p className="text-sm text-muted-foreground">{contact.phone}</p>
                    </div>
                    <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-success text-white shadow-lg shadow-success/30">
                      <Phone className="h-4 w-4" />
                    </span>
                  </a>
                ))}
              </div>
            </GlassCard>
          </motion.div>
        )}

        <motion.p
          variants={fadeUp}
          className="flex items-center justify-center gap-1.5 pt-3 text-xs text-muted-foreground"
        >
          <HeartPulse className="h-3.5 w-3.5 text-primary" />
          Powered by ResQLink · Connecting Lives During Emergencies
        </motion.p>
      </motion.div>
    </div>
  )
}
